### ISSUE TITLE
Namespace definitions are not handled correctly inside @payload element

### ISSUE THREAD

**Issue by tishan89** [siddhi-io/siddhi-map-xml#35] opened 2018-11-03 07:18 UTC
**Description:**
When we add a namespace inside @payload element
Ex: 
```
@sink(type='http', publisher.url='http://192.168.1.5:8280/services/echo', method='POST',headers="'Content-Type:text/xml','SOAPAction:urn:echoInt'",
    @map(type='xml',
        @payload( "<soapenv:Envelope xmlns:echo='http://echo.services.core.carbon.wso2.org' xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/'><soapenv:Header/><soapenv:Body><echo:echoInt><in>{{attr1}}</in></echo:echoInt></soapenv:Body></soapenv:Envelope>")
    )
)
```
This will cause outbound request to drop quotes around namespace URL. Ex:
`<soapenv:Envelope xmlns:echo=http://echo.services.core.carbon.wso2.org xmlns:soapenv=http://schemas.xmlsoap.org/soap/envelope/><soapenv:Header/><soapenv:Body><echo:echoInt><in>2</in></echo:echoInt></soapenv:Body></soapenv:Envelope>`

**Affected Product Version:**
4.0.0 and above

**Steps to reproduce:**
Use above sink or look alike sink config with namespace defined inside @payload

**Comment by mohanvive** [comment] 2019-09-25 16:14
Tested with below Siddhi app in the latest siddhi-map-xml implementation but not able to reproduce it.

```
@App:name("SiddhiApp")
@App:description("Description of the plan")

define stream FooStream (id int, symbol string, price float, volume long); 

@sink(type='log',  @map(type='xml', @payload("<soapenv:Envelope xmlns:echo='http://echo.services.core.carbon.wso2.org' xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/'><soapenv:Header/><soapenv:Body><echo:echoInt><in>{{symbol}}</in></echo:echoInt></soapenv:Body></soapenv:Envelope>\"))) 
define stream BarStream (id int, symbol string, price float, volume long);

from FooStream
select id, symbol, price, volume
insert into BarStream;
```

See the output below,

<img width="1429" alt="Screen Shot 2019-09-25 at 9 43 40 PM" src="https://user-images.githubusercontent.com/7523274/65619337-9b6eb100-dfdd-11e9-9e91-546e21c03731.png">

**Comment by mohanvive** [comment] 2019-09-25 16:15
Closing the issue since it is not reproducible with latest version. Please reopen if you need further assistance on this..

**Closed by mohanvive** 2019-09-25 16:14 UTC
Labels: priority/high, severity/critical
